my_list=[]
my_list.append([10,20,30,40])
print("my appended list is:",my_list)
my_list.insert(1,15)
print("my inserted list is:",my_list)
my_list.extend([50,60,70])
print("my extended list is:",my_list)
my_list.pop()
print("removed list is:",my_list)
my_list.sort()
print("sorted list is:",my_list)
